### ISSUE TITLE
More Branches Please

### ISSUE THREAD

**Issue by clozinski** [zopefoundation/groktoolkit#3]
Thank you enormously for keeping this up to date. Makes my life so much easier. 

There are currently only two branches here. Master and resurrection sprint.  Nor could I find groktoolkit on PyPi.  It makes it a bit tricky to base something on this, because if it changes it could break my production servers.  So instead I copy the grok.cfg and ztk.cfg to my project.  Not good.  

I would be grateful if you would be so kind as to give the current version a name, then I could just add it to my buildout.cfg.  Other than that thank you.

**Comment by icemac** [comment]
This is what tags are for. There are 17 of them in this repository. Okay, the newest is from 2012 but there have not been that many changes since than.

zopefoundation/zopetoolkit even gave up on creating new releases and encourages the users of it to copy the versions file and maintain it manually. See https://zopetoolkit.readthedocs.io/en/latest/#installation

I am closing this issue as I do not see what can be done to fix it.
